# 
#
#
#
#
#
#
#
#       ------   ----------------   ------
#      | 2001 | |      2002      | | 2003 |     (200cm)
#       ------   ----------------   ------
#
#
#       ------   ----------------   ------
#      | 1001 | |      1002      | | 1003 |     (100cm)
#       ------   ----------------   ------
#
#
#         -----   ---------------   -----
#        | 501 | |      502      | | 503 |      (50cm)
#         -----   ---------------   -----
#
#                    --\___/--    
#                    |       |
#                    |       |  
#                    ---------

uint8 depth_percept_ready

uint8 is_obstacle_area_501
uint8 is_obstacle_area_502
uint8 is_obstacle_area_503
uint8 is_obstacle_area_1001
uint8 is_obstacle_area_1002
uint8 is_obstacle_area_1003
uint8 is_obstacle_area_2001
uint8 is_obstacle_area_2002
uint8 is_obstacle_area_2003
